/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "https://localhost:8080".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *  
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 * 
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 * 
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface Sample
 */
export interface Sample {
    /**
     * 
     * @type {string}
     * @memberof Sample
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof Sample
     */
    timestamp?: number;
}


/**
 * DemoControllerApi - fetch parameter creator
 * @export
 */
export const DemoControllerApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary getUser
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserUsingGET(options: any = {}): FetchArgs {
            const localVarPath = `/user`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DemoControllerApi - functional programming interface
 * @export
 */
export const DemoControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary getUser
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserUsingGET(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Sample> {
            const localVarFetchArgs = DemoControllerApiFetchParamCreator(configuration).getUserUsingGET(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * DemoControllerApi - factory interface
 * @export
 */
export const DemoControllerApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @summary getUser
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserUsingGET(options?: any) {
            return DemoControllerApiFp(configuration).getUserUsingGET(options)(fetch, basePath);
        },
    };
};

/**
 * DemoControllerApi - object-oriented interface
 * @export
 * @class DemoControllerApi
 * @extends {BaseAPI}
 */
export class DemoControllerApi extends BaseAPI {
    /**
     * 
     * @summary getUser
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DemoControllerApi
     */
    public getUserUsingGET(options?: any) {
        return DemoControllerApiFp(this.configuration).getUserUsingGET(options)(this.fetch, this.basePath);
    }

}

